### PR TITLE
Auto Image

### PR DESCRIPTION
**Pull request by jbrooksuk**
I've made changes so that AnyStretch will use the image source from the `data-stretch` attribute (which can be changed in the settings object). This is much easier to use if you're dynamically outputting your image list with, say PHP or Ruby.

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Nothing?

**Comment by HandHugs** [comment]
Did you make this change? Is it in the files I just downloaded? This would be really useful if I didn't have to put the source of the image into the script - I am trying to use this on a wordpress site and would like it if I could apply this to every image with a certain class.

**Comment by jbrooksuk** [comment]
@HandHugs sorry for the late reply. The pull request hasn't been made yet, so the code won't be working. We need to nudge @danmillar as it's been a year now.

**Comment by jbrooksuk** [comment]
Cheers @danmillar! @HandHugs it's now merged and ready to use :+1:

**Comment by danmillar** [comment]
Crumbs...time flies! Consider me nudged :)

**Pull request merged**
