### PR TITLE
Bower compatibility

### PR DESCRIPTION
**Pull request by peschee**
Hi

I have added a `bower.json` file in order for your library to be compatible with [Bower](http://bower.io/).

### CODE REVIEW

**Comment by pzi** [comment]
+1

**Comment by peschee** [comment]
This PR is 5 months old. Are you still maintaining this project @danmillar ?

**Comment by peschee** [comment]
That was fast ;) Thanks.

**Comment by danmillar** [comment]
Sorry I didn't do this sooner :)

**Comment by pzi** [comment]
Great stuff! :)

**Comment by llahnoraa** [comment]
Off topic... 

I ran into accessibility issue `<div class="example-class" data-stretch="example-image.jpg">` - it's looking for `alt` tag but I can't add `alt` tag inside `div`

Any solution?

**Comment by pzi** [comment]
@llahnoraa this has nothing to do with this PR. Maybe create a new issue?

**Comment by llahnoraa** [comment]
There is no "Issue" button on your page anywhere. Did you disabled it?

**Comment by llahnoraa** [comment]
@pzi there is still no "Issue" button anywhere on your Git page. Please advise. Thanks!

**Comment by pzi** [comment]
It's not my Git repository, however, issues can be found here:

image


Or via direct link: https://github.com/danmillar/jquery-anystretch/issues/new

**Pull request merged**
